config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :recipes, only: %i[index show new create destroy]
  resources :foods, only: %i[index new create destroy]

  get '/public_recipes', to: 'recipes#public_recipes'
  get '/shopping_list', to: 'shopping_list#index'
  get '/recipes/:id/new_ingredient', to: 'recipes#new_ingredient', as: 'recipes_add_ingredient'
  post '/recipes/:id/new_ingredient', to: 'recipes#add_ingredient', as: 'recipes_add_ingredient_post'
  get '/recipes/:id/edit_ingredient', to: 'recipes#edit_ingredient', as: 'recipe_edit_ingredient'
  put '/recipes/:id/edit_ingredient', to: 'recipes#update_ingredient', as: 'recipe_edit_ingredient_put'
  delete '/recipes/:id/delete_ingredient', to: 'recipes#destroy_ingredient', as: 'recipes_delete_ingredient'
  put '/recipes/:id/toggle_status', to: 'recipes#toggle', as: 'recipes_toggle'

  root 'recipes#public_recipes'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    can :manage, :all, user_id: user.id if user.role == 'user'
    can :read, Recipe, public: true
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :recipes, through: :recipe_foods

  validates :name, :measurement_unit, :quantity, presence: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :foods, through: :recipe_foods

  validates :name, presence: true
  validates :preparation_time, numericality: { greater_than: 0 }
  validates :cooking_time, numericality: { greater_than: 0 }
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :recipes, dependent: :destroy
  has_many :foods, dependent: :destroy

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, :update_allowed_parameters, if: :devise_controller?

  rescue_from CanCan::AccessDenied do |exception|
    flash[:warning] = exception.message
    redirect_to recipes_path
  end

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :authenticate_user!, only: %i[index new create destroy]
  before_action :set_food, only: %i[show edit update destroy]

  # GET /foods or /foods.json
  def index
    @foods = if current_user
               current_user.foods
             else
               Food.all
             end
  end

  # GET /foods/new
  def new
    @food = Food.new
    @recipe_id = params[:recipe_id]
  end

  # POST /foods or /foods.json
  def create
    @food = current_user.foods.build(food_params.except(:recipe_id))
    if @food.save
      redirect_to foods_path, notice: 'Food was successfully created.'
    else
      redirect_to new_food_path, notice: 'Food was not successfully created.'
    end
  end

  # DELETE /foods/1 or /foods/1.json
  def destroy
    @food.destroy

    respond_to do |format|
      format.html { redirect_to foods_url, notice: 'Food was successfully destroyed.' }
    end
  end

  # GET /shopping_list
  def shopping_list
    @user = current_user

    render :shopping_list
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_food
    @food = Food.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity, :recipe_id)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  load_and_authorize_resource
  before_action :set_recipe,
                only: %i[show destroy new_ingredient add_ingredient edit_ingredient update_ingredient
                         destroy_ingredient toggle]

  # GET /public_recipes
  def public_recipes
    @recipes = Recipe.where(public: true)
  end

  # GET /recipes or /recipes.json
  def index
    return unless user_signed_in?

    @recipes = Recipe.where(user: current_user.id)
  end

  # GET /recipes/1 or /recipes/1.json
  def show
    @foods = Food.all
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # POST /recipes or /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipe_path(id: @recipe), notice: 'Recipe was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # Select a new ingredient for a recipe
  # GET /recipes/1/new_ingredient
  def new_ingredient
    @recipe_food = RecipeFood.new

    render :new_ingredient
  end

  # POST /recipes/1/new_ingredient
  def add_ingredient
    @food = RecipeFood.new(ingredient_params)

    respond_to do |format|
      if @food.save
        format.html do
          if @food.recipe.present?
            redirect_to recipe_path(id: @recipe), notice: 'Ingredient was successfully added.'
          else
            redirect_to foods_path, notice: 'Ingredient was successfully added.'
          end
        end
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # GET /recipes/1/recipe_edit_ingredient
  def edit_ingredient
    @recipe_food = RecipeFood.new
  end

  # PUT /recipes/1/update_ingredient
  def update_ingredient
    if @recipe.recipe_foods.find(params[:recipe_food][:id]).update(ingredient_params_update)
      redirect_to recipe_path(id: @recipe), notice: 'Ingredient was successfully updated.'
    else
      format.html { render :new, status: :unprocessable_entity }
    end
  end

  # DELETE /recipes/1/delete_ingredient
  def destroy_ingredient
    if @recipe.recipe_foods.find(params[:recipe_foods_id]).destroy
      redirect_to recipe_path(id: @recipe), notice: 'Ingredient was successfully deleted.'
    else
      format.html { render :new, status: :unprocessable_entity }
    end
  end

  # DELETE /recipes/1
  def destroy
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_path, notice: 'Recipe was successfully deleted.' }
    end
  end

  def toggle
    if @recipe.public
      @recipe.update(public: false)
    else
      @recipe.update(public: true)

    end
  end

  private

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public).merge(
      user_id: current_user.id
    )
  end

  def ingredient_params
    food_id = params[:recipe_food][:food_select].to_s.split('-').first.rstrip.to_i
    params[:id]
    params.require(:recipe_food).permit(:quantity).merge(food_id:).merge(recipe_id: params[:id])
  end

  def ingredient_params_update
    params.require(:recipe_food).permit(:id, :quantity)
  end
end

app/controllers/shopping_list_controller.rb
class ShoppingListController < ApplicationController
  before_action :authenticate_user!
  def index
    user = current_user
    @missing_foods = []
    @total_price = 0

    user.recipes.includes(recipe_foods: :food).each do |recipe|
      recipe.recipe_foods.each do |recipe_food|
        available_food = recipe_food.food
        next unless available_food && available_food.quantity < recipe_food.quantity

        missing_quantity = recipe_food.quantity - available_food.quantity
        missing_food = MissingFoodDecorator.new(available_food, missing_quantity)
        @missing_foods << missing_food

        @total_price += missing_food.price * missing_food.quantity
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index; end

  def show; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
  def food_names
    Food.all.where(user_id: current_user.id).map { |food| "#{food.id} - #{food.name}" }
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/foods/_food.html.erb
<div id="<%= dom_id food %>">
</div>

app/views/foods/_form.html.erb
<%= form_with(model: food) do |form| %>

  <%= form.hidden_field :recipe_id, value: @recipe_id %>

  <% if food.errors.any? %>
    <div class="bg-red-400 text-white text-center text-sm mb-10 rounded-md">
      <h2><%= pluralize(food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
        <% food.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="py-8 ml-10">
    <form class="w-full max-w-sm mx-auto bg-white p-8 rounded-md shadow-md">

      <div class="mb-4">
        <%= form.label :name, class: "block text-gray-700 text-sm font-bold mb-2" %>
        <%= form.text_field :name, class: "w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:border-indigo-500" %>
      </div>

      <div class="mb-4">
        <%= form.label :measurement_unit, class: "block text-gray-700 text-sm font-bold mb-2" %>
        <%= form.text_field :measurement_unit, class: "w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:border-indigo-500"%>
      </div>

      <div class="mb-4">
        <%= form.label :price, class: "block text-gray-700 text-sm font-bold mb-2" %>
        <%= form.text_field :price, class: "w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:border-indigo-500" %>
      </div>

      <div class="mb-4">
        <%= form.label :quantity, class: "block text-gray-700 text-sm font-bold mb-2" %>
        <%= form.number_field :quantity, class: "w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:border-indigo-500" %>
      </div>

      <button class="btn-primary">
        <%= form.submit %>
      </button>
    </form>
  </div>
<% end %>

app/views/foods/edit.html.erb
<h1>Editing food</h1>

<%= render "form", food: @food %>

<br>

<div>
  <%= link_to "Show this food", @food %> |
  <%= link_to "Back to foods", foods_path %>
</div>

app/views/foods/index.html.erb
<div><%= notice %></div>
<div><%= alert %></div>
<div class="flex flex-col items-center my-10 ml-10">
  <%= link_to "New food", new_food_path, class: "self-end mb-5 btn-primary" %>
  <table class="w-full border-collapse">
    <thead>
      <tr class="bg-gray-300">
        <th class="p-4 text-left">Food</th>
        <th class="p-4 text-left">Quantity</th>
        <th class="p-4 text-left">Measurement Unit</th>
        <th class="p-4 text-left">Unit Price</th>
        <th class="p-4 text-left">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% if @foods.present? %>
        <% @foods.reverse.each do |food| %>
          <tr class="border border-2 ">
            <td class="p-4"><%= food.name %></td>
            <td class="p-4"><%= food.quantity %></td>
            <td class="p-4"><%= food.measurement_unit %></td>
            <td class="p-4"><%= food.price %></td>
            <td class="p-4">
              <%= button_to "delete",
              food_path(food.id),
              data: {
                confirm: "Are you sure?"
              },
              method: :delete,
              class: "hover:underline" %>
            </td>
          </tr>
        <% end %>
      <% else %>
        <tr>
          <td colspan="4" class="p-4 text-center">No Food Found</td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/foods/new.html.erb
<h1 class="title">New food</h1>

<%= render "form", food: @food %>

<div><%= notice %></div>
<div><%= alert %></div>

<div>
  <%= link_to "Back to foods", foods_path, class: "btn-secondary ml-10" %>
</div>

app/views/foods/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @food %>

<div>
  <%= link_to "Edit this food", edit_food_path(@food) %> |
  <%= link_to "Back to foods", foods_path %>

  <%= button_to "Destroy this food", @food, method: :delete %>
</div>

app/views/layouts/_header.html.erb
<header class="w-full text-gray-700 bg-white shadow-sm body-font">
  <div class="container flex flex-col items-start p-6 mx-auto md:flex-row">

    <a
      href="/public_recipes"
      class="
        flex
        items-center
        text-xl
        italic
        mb-4
        font-medium
        text-gray-800
        title-font
        md:mb-0
      "
    >
      RailsRecipes
    </a>
    <nav class="flex items-center justify-center text-base md:ml-auto">
      <a href="/recipes" class="mr-5 font-medium hover:text-gray-900">My Recipes</a>
      <a href="/public_recipes" class="mr-5 font-medium hover:text-gray-900">Public Recipes</a>
      <a href="/foods" class="mr-5 font-medium hover:text-gray-900">Foods</a>
      <a href="/shopping_list" class="font-medium hover:text-gray-900">Shopping List</a>
    </nav>
    <% if current_user %>
      <div class="items-center h-full pl-6 ml-6 border-l border-gray-200 flex">
        <%= button_to "Logout",
        destroy_user_session_path,
        method: :delete,
        class: "mr-5 font-medium hover:text-gray-900" %>
        <a
          href="/recipes"
          class="
            px-4
            py-2
            text-xs
            font-bold
            text-white
            uppercase
            transition-all
            duration-150
            bg-teal-500
            rounded
            shadow
            outline-none
            active:bg-teal-600
            hover:shadow-md
            focus:outline-none
            ease
          "
        >
          <%= current_user.name %>
        </a>
      </div>
    <% else %>
      <div class="items-center h-full pl-6 ml-6 border-l border-gray-200">
        <a href="/users/sign_in" class="mr-5 font-medium hover:text-gray-900">Login</a>
        <a
          href="/users/sign_up"
          class="
            px-4
            py-2
            text-xs
            font-bold
            text-white
            uppercase
            transition-all
            duration-150
            bg-teal-500
            rounded
            shadow
            outline-none
            active:bg-teal-600
            hover:shadow-md
            focus:outline-none
            ease
          "
        >
          Sign Up
        </a>
      </div>
    <% end %>

  </div>
</header>

app/views/layouts/_toggle-input.html.erb
<label class="switch">
    <input type="checkbox">
    <span class="slider"></span>
</label>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-gray-100">
    <%= render "layouts/header" %>
    <div class="container"><%= yield %></div>
  </body>
</html>

app/views/recipes/_form.html.erb
<%= form_with model: @recipe, url: recipes_path, method: :post do |form| %>
  <% if recipe.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="py-8 ml-10">
    <form class="w-full max-w-sm mx-auto bg-white p-8 rounded-md shadow-md">

      <div class="mb-4">
        <%= form.label :name, class:'block text-gray-700 text-sm font-bold mb-2' %>
        <%= form.text_field :name, autofocus: true, autocomplete: "name", class:'w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:border-indigo-500' %>
      </div>

      <div class="mb-4">
        <%= form.label :preparation_time, "Preparation time (hours)", class:'block text-gray-700 text-sm font-bold mb-2'%>
        <%= form.number_field :preparation_time, in: 1.0..8.0, step: 0.25, class:'w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:border-indigo-500' %>
      </div>

      <div class="mb-4">
        <%= form.label :cooking_time, "Cooking time (hours)", class:'block text-gray-700 text-sm font-bold mb-2'%>
        <%= form.number_field :cooking_time, in: 1.0..8.0, step: 0.25, class:'w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:border-indigo-500' %>
      </div>

      <div class="mb-4">
        <%= form.label :description, class:'block text-gray-700 text-sm font-bold mb-2' %>
        <%= form.text_area :description, autocomplete: "description", class:'w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:border-indigo-500' %>
      </div>

      <div class="mb-4">
        <p class='block text-gray-700 text-sm font-bold mb-2'>Public recipe?</p>
        <label class="switch">
          <%= form.check_box :public, class:"checkbox" %>
          <span class="slider"></span>
        </label>
      </div>



      <button class="btn-primary">
        <%= form.submit %>
      </button>
    </form>
  </div>
<% end %>

app/views/recipes/_recipe.html.erb
<div class="ml-10 mt-8 mb-5">
  <h1 class="text-center text-2xl font-bold"><%= recipe.name %></h1>
  <div class="flex flex-col gap-2 my-5 mb-5">
    <div class="flex justify-between">
      <p><strong>Preparation Time:
        </strong><%= pluralize(recipe.preparation_time, "hour") %></p>
      <div>
        <%= form_with url: recipes_toggle_path, method: :put do |form| %>
          <p class="text-center font-bold text-lg mb-1 toggle_p">
            <%= recipe.public? ? "Public" : "Private" %>
          </p>
          <% if can? :destroy, recipe %>
            <label class="switch">
              <%= form.check_box :public,
                             id: "toggle",
                             checked: recipe.public?,
                             onchange: "this.form.submit();" %>
              <span class="slider"></span>
            </label>
          <% else %>
            <label class="switch">
              <%= form.check_box :public,
                             id: "toggle",
                             checked: recipe.public?,
                             disabled: true,
                             onchange: "this.form.submit();" %>
              <span class="slider"></span>
            </label>
          <% end %>
        <% end %>
      </div>

    </div>
    <p><strong>Cooking Time:
      </strong><%= pluralize(recipe.cooking_time, "hour") %></p>
    <p><strong>Steps:
      </strong><%= recipe.description %></p>
    <div class="flex justify-between">
      <%= button_to "Generate shopping list",
      recipes_path,
      class: "btn-secondary",
      id: "my_id",
      method: :get,
      onclick: "alert('Input collected!')" %>
      <% if can? :destroy, recipe %>
        <%= button_to "Add ingredient",
        recipes_add_ingredient_path,
        method: :get,
        class: "btn-primary" %>
      <% end %>
    </div>
  </div>

  <hr>

  <table class="w-full border-collapse mt-5">
    <thead>
      <tr class="bg-gray-300">
        <th class="p-4 text-left">Food</th>
        <th class="p-4 text-left">Quantity</th>
        <th class="p-4 text-left">Unit Price</th>
        <th class="p-4 text-left">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% if recipe.foods %>
        <% recipe.recipe_foods.includes(:food).each do |recipe_food| %>
          <tr class="border border-2 ">
            <td class="p-4"><%= recipe_food.food.name %></td>
            <td class="p-4"><%= "#{pluralize(recipe_food.quantity, recipe_food.food.measurement_unit)}" %></td>
            <td class="p-4"><%= recipe_food.food.price %></td>
            <td class="p-4">
              <%= link_to "Modify",
              recipe_edit_ingredient_path(
                edit_params: {
                  recipe_foods_id: recipe_food.id,
                  recipe_foods_food_id: recipe_food.food_id,
                  recipe_foods_quantity: recipe_food.quantity,
                  recipe_foods_food_name: recipe_food.food.name
                }
              ),
              method: :put,
              class: "hover:underline" %>
              <%= button_to "Remove",
              recipes_delete_ingredient_path(recipe_foods_id: recipe_food.id),
              method: :delete,
              class: "hover:underline" %>
            </td>
          </tr>
        <% end %>
      <% else %>
        <tr>
          <td colspan="4" class="p-4 text-center">No Food Found</td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<%= javascript_include_tag "toggle" %>

app/views/recipes/_recipe_card.html.erb
<div class="flip-card">
  <div class="flip-card-inner ">
    <div class="flip-card-front px-3">
      <p class="font-bold text-xl"><%= "Recipe #{recipe.id}" %></p>
      <p class="text-lg"><%= recipe.name %></p>
    </div>
    <div class="flip-card-back px-3">
      <a href="<%= recipe_path(id: recipe.id) %>">
        <p class="text-lg font-bold mb-2"><%= recipe.name %></p>
        <p class=""><%= "#{recipe.description[0..100]}..." %></p>
      </a>
      <%= button_to "Remove",
      recipe_path(id: recipe.id),
      method: :delete,
      class: "mt-5 font-bold text-lg hover:underline hover:text-red-600" %>
    </div>
  </div>
</div>

app/views/recipes/edit_ingredient.html.erb
<%= form_with model: @recipe_food, url: recipe_edit_ingredient_put_path, method: :put do |form| %>
  <div class="w-full max-w-sm mx-auto bg-white p-8 rounded-lg shadow-md mt-10">
    <div class="mb-4">
      <%= form.label :food, class: "block text-gray-700 text-sm font-bold mb-2" %><br/>
      <%= form.text_field :food,
                      value: params[:edit_params][:recipe_foods_food_name],
                      disabled: true,
                      class:
                        "w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:border-indigo-500" %>
    </div>

    <div class="field">
      <%= form.label :quantity, class: "block text-gray-700 text-sm font-bold mb-2" %><br/>
      <%= form.number_field :quantity,
                        value: params[:edit_params][:recipe_foods_quantity],
                        class:
                          "w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:border-indigo-500" %>
    </div>

    <%= form.hidden_field :id, value: params[:edit_params][:recipe_foods_id] %>

    <%= form.submit "Edit quantity", class: "btn-primary mt-5" %>
  </div>

<% end %>

app/views/recipes/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="container flex flex-col">
  <h1 class="title ml-10">Recipes</h1>

  <%= link_to "New recipe", new_recipe_path, class: "btn-primary self-end" %>

  <div
    id="recipes"
    class="
      grid
      sm:grid-cols-2
      lg:grid-cols-3
      xl:grid-cols-4
      gap-10
      mt-10
      ml-10
    "
  >
    <% @recipes.each do |recipe| %>
      <%= render "recipe_card", recipe: recipe %>
    <% end %>
  </div>
</div>

app/views/recipes/new.html.erb
<h1 class="title">New recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Back to recipes", recipes_path, class:"btn-secondary ml-10" %>
</div>

app/views/recipes/new_ingredient.html.erb
<%= form_with model: @recipe_food, url: recipes_add_ingredient_post_path, method: :post do |form| %>
  <div class="w-full max-w-sm mx-auto bg-white p-8 rounded-lg shadow-md mt-10">
    <%= form.select :food_select,
                food_names,
                {},
                class:
                  "w-full px-3 mt-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:border-indigo-500" %>
    <%= form.number_field :quantity,
                      class:
                        "w-full px-3 mt-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:border-indigo-500" %>
    <%= form.submit "Add Ingredient", class: "btn-primary mt-5" %>
  </div>

<% end %>

app/views/recipes/public_recipes.html.erb
<p style="color: green"><%= notice %></p>

<div class="container flex flex-col">
  <h1 class="title ml-10">Recipes</h1>

  <%= link_to "New recipe", new_recipe_path, class: "btn-primary self-end" %>

  <div
    id="recipes"
    class="
      grid
      sm:grid-cols-2
      lg:grid-cols-3
      xl:grid-cols-4
      gap-10
      mt-10
      ml-10
    "
  >
    <% @recipes.each do |recipe| %>
      <%= render "recipe_card", recipe: recipe %>
    <% end %>
  </div>
</div>

app/views/recipes/show.html.erb
<div class='mb-10'>
  <p style="color: green"><%= notice %></p>

  <%= render @recipe %>

  <%= link_to "Back to recipes", recipes_path, class: "btn-secondary ml-10" %>
</div>

app/views/shopping_list/index.html.erb
<div class="container ml-10 flex flex-col">
  <h1 class="title">Shopping List</h1>
  <div class="flex mt-5 justify-between">
    <h3 class="text-lg"><strong>Amount of food items to buy:</strong>
      <%= @missing_foods.length %>
    </h3>
    <h3 class="text-lg"><strong>Total cost of the food needed:</strong>
      $<%= @total_price %>
    </h3>
  </div>

  <table class="mt-10">
    <thead>
      <tr class="bg-gray-400">
        <th class="p-4 text-left">Food</th>
        <th class="p-4 text-left">Quantity</th>
        <th class="p-4 text-left">Measurement Unit</th>
        <th class="p-4 text-left">Price</th>
      </tr>
    </thead>
    <tbody>
      <% @missing_foods.each do |missing_food| %>
        <tr class="border border-2">
          <td class="p-4"><%= missing_food.name %></td>
          <td class="p-4"><%= missing_food.quantity %></td>
          <td class="p-4"><%= missing_food.measurement_unit %></td>
          <td class="p-4"><%= missing_food.price %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>